/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import DAO.CPUDAO;
import DAO.ImpresoraDAO;
import DAO.MarcaDAO;
import DAO.MonitorDAO;
import DAO.PersonasDAO;
import Teclado.Teclado;
import VistaCPU.AgregarCPUUI;
import VistaCPU.BuscarCPUUI;
import VistaCPU.ListarCPUUI;
import VistaImpresoras.AgregarImpresoraUI;
import VistaImpresoras.BuscarImpresoraUI;
import VistaImpresoras.ListarImpresoraUI;
import VistaMonitor.AgregarMoniUI;
import VistaMonitor.BuscarMoniUI;
import VistaMonitor.ListarMonitorUI;
import VistaPersonas.AgregarPersonasUI;
import VistaPersonas.BuscarPersonasUI;
import VistaPersonas.ListarPersonasUI;
import javax.swing.JPanel;

/**
 *
 * @author Paula
 */
public class Grafico extends javax.swing.JFrame {

    Teclado TE = new Teclado();
    private MonitorDAO LosMoni = new MonitorDAO();
    private PersonasDAO LasPersonas = new PersonasDAO();
    private ImpresoraDAO LasImpresoras = new ImpresoraDAO();
    private CPUDAO LosCpu = new CPUDAO();
    private JPanel todos;
    private MarcaDAO LasMarcas= new MarcaDAO();

    private void cambio(JPanel vista) {
        try {
            this.getContentPane().remove(todos);
        } catch (Exception e) {
        }
        todos = vista;
        todos.setBounds(0, 0, this.getWidth(), this.getHeight());
        this.getContentPane().add(todos);
        this.repaint();
        this.pack();
    }

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JM_Archivo = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JMI_Salir = new javax.swing.JMenuItem();
        JM_Monitor = new javax.swing.JMenu();
        JMI_AgregarMoni = new javax.swing.JMenuItem();
        JMI_ListarMoni = new javax.swing.JMenuItem();
        JMI_BuscarMoni = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMI_GuardarMoni = new javax.swing.JMenuItem();
        JM_CPU = new javax.swing.JMenu();
        JMI_AgregarCPU = new javax.swing.JMenuItem();
        JMI_ListarCPU = new javax.swing.JMenuItem();
        JMI_BuscarCPU = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        JMI_GuardarCPU = new javax.swing.JMenuItem();
        JM_Impresora = new javax.swing.JMenu();
        JMI_AgregarImpr = new javax.swing.JMenuItem();
        JMI_ListarImpr = new javax.swing.JMenuItem();
        JMI_BuscarImpr = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        JMI_GuardarImpr = new javax.swing.JMenuItem();
        JM_Persona = new javax.swing.JMenu();
        JMI_AgregarPers = new javax.swing.JMenuItem();
        JMI_ListarPers = new javax.swing.JMenuItem();
        JMI_BuscarPers = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        JMI_GuardarPers = new javax.swing.JMenuItem();
        JM_Gestion = new javax.swing.JMenu();
        JMI_Gestion = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        JMI_GuardarPers1 = new javax.swing.JMenuItem();
        JM_Ayuda = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        JMI_Acercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JM_Archivo.setText("Archivo");
        JM_Archivo.add(jSeparator2);

        JMI_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        JMI_Salir.setText("Salir");
        JMI_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SalirActionPerformed(evt);
            }
        });
        JM_Archivo.add(JMI_Salir);

        jMenuBar1.add(JM_Archivo);

        JM_Monitor.setText("Monitor");

        JMI_AgregarMoni.setText("Agregar");
        JMI_AgregarMoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AgregarMoniActionPerformed(evt);
            }
        });
        JM_Monitor.add(JMI_AgregarMoni);

        JMI_ListarMoni.setText("Listar");
        JMI_ListarMoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ListarMoniActionPerformed(evt);
            }
        });
        JM_Monitor.add(JMI_ListarMoni);

        JMI_BuscarMoni.setText("Buscar");
        JMI_BuscarMoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BuscarMoniActionPerformed(evt);
            }
        });
        JM_Monitor.add(JMI_BuscarMoni);
        JM_Monitor.add(jSeparator1);

        JMI_GuardarMoni.setText("Guardar");
        JMI_GuardarMoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GuardarMoniActionPerformed(evt);
            }
        });
        JM_Monitor.add(JMI_GuardarMoni);

        jMenuBar1.add(JM_Monitor);

        JM_CPU.setText("CPU");

        JMI_AgregarCPU.setText("Agregar");
        JMI_AgregarCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AgregarCPUActionPerformed(evt);
            }
        });
        JM_CPU.add(JMI_AgregarCPU);

        JMI_ListarCPU.setText("Listar");
        JMI_ListarCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ListarCPUActionPerformed(evt);
            }
        });
        JM_CPU.add(JMI_ListarCPU);

        JMI_BuscarCPU.setText("Buscar");
        JMI_BuscarCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BuscarCPUActionPerformed(evt);
            }
        });
        JM_CPU.add(JMI_BuscarCPU);
        JM_CPU.add(jSeparator4);

        JMI_GuardarCPU.setText("Guardar");
        JMI_GuardarCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GuardarCPUActionPerformed(evt);
            }
        });
        JM_CPU.add(JMI_GuardarCPU);

        jMenuBar1.add(JM_CPU);

        JM_Impresora.setText("Impresora");

        JMI_AgregarImpr.setText("Agregar");
        JMI_AgregarImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AgregarImprActionPerformed(evt);
            }
        });
        JM_Impresora.add(JMI_AgregarImpr);

        JMI_ListarImpr.setText("Listar");
        JMI_ListarImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ListarImprActionPerformed(evt);
            }
        });
        JM_Impresora.add(JMI_ListarImpr);

        JMI_BuscarImpr.setText("Buscar");
        JMI_BuscarImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BuscarImprActionPerformed(evt);
            }
        });
        JM_Impresora.add(JMI_BuscarImpr);
        JM_Impresora.add(jSeparator5);

        JMI_GuardarImpr.setText("Guardar");
        JMI_GuardarImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GuardarImprActionPerformed(evt);
            }
        });
        JM_Impresora.add(JMI_GuardarImpr);

        jMenuBar1.add(JM_Impresora);

        JM_Persona.setText("Personas");

        JMI_AgregarPers.setText("Agregar");
        JMI_AgregarPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AgregarPersActionPerformed(evt);
            }
        });
        JM_Persona.add(JMI_AgregarPers);

        JMI_ListarPers.setText("Listar");
        JMI_ListarPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ListarPersActionPerformed(evt);
            }
        });
        JM_Persona.add(JMI_ListarPers);

        JMI_BuscarPers.setText("Buscar");
        JMI_BuscarPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BuscarPersActionPerformed(evt);
            }
        });
        JM_Persona.add(JMI_BuscarPers);
        JM_Persona.add(jSeparator6);

        JMI_GuardarPers.setText("Guardar");
        JMI_GuardarPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GuardarPersActionPerformed(evt);
            }
        });
        JM_Persona.add(JMI_GuardarPers);

        jMenuBar1.add(JM_Persona);

        JM_Gestion.setText("Gestion");

        JMI_Gestion.setText("Gestion");
        JMI_Gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GestionActionPerformed(evt);
            }
        });
        JM_Gestion.add(JMI_Gestion);
        JM_Gestion.add(jSeparator7);

        JMI_GuardarPers1.setText("Guardar");
        JMI_GuardarPers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_GuardarPers1ActionPerformed(evt);
            }
        });
        JM_Gestion.add(JMI_GuardarPers1);

        jMenuBar1.add(JM_Gestion);

        JM_Ayuda.setText("Ayuda");
        JM_Ayuda.add(jSeparator3);

        JMI_Acercade.setText("Acerca de");
        JMI_Acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AcercadeActionPerformed(evt);
            }
        });
        JM_Ayuda.add(JMI_Acercade);

        jMenuBar1.add(JM_Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SalirActionPerformed
        // TODO add your handling code here:
        TE.Msn("Adios...");
        System.exit(0);
    }//GEN-LAST:event_JMI_SalirActionPerformed

    private void JMI_AcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AcercadeActionPerformed
        // TODO add your handling code here:
        TE.Msn("Sistema de informacion desarrollado en la CUN");
    }//GEN-LAST:event_JMI_AcercadeActionPerformed

    private void JMI_AgregarMoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AgregarMoniActionPerformed
        // TODO add your handling code here:
        this.cambio(new AgregarMoniUI(this.LosMoni, this.LasMarcas));
    }//GEN-LAST:event_JMI_AgregarMoniActionPerformed

    private void JMI_ListarMoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ListarMoniActionPerformed
        // TODO add your handling code here:
        this.cambio(new ListarMonitorUI(this.LosMoni, this.LasMarcas));
    }//GEN-LAST:event_JMI_ListarMoniActionPerformed

    private void JMI_BuscarMoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BuscarMoniActionPerformed
        // TODO add your handling code here:
        this.cambio(new BuscarMoniUI(this.LosMoni, this.LasMarcas));
    }//GEN-LAST:event_JMI_BuscarMoniActionPerformed

    private void JMI_GuardarMoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GuardarMoniActionPerformed
        // TODO add your handling code here:
        if(this.LosMoni.Guardar()){
            this.TE.Msn("El archivo se Guardo");
        }else{
            this.TE.Msn("No tiene Permisos");
        }
    }//GEN-LAST:event_JMI_GuardarMoniActionPerformed

    private void JMI_AgregarCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AgregarCPUActionPerformed
        // TODO add your handling code here:
        this.cambio(new AgregarCPUUI(this.LosCpu, this.LasMarcas));
    }//GEN-LAST:event_JMI_AgregarCPUActionPerformed

    private void JMI_ListarCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ListarCPUActionPerformed
        // TODO add your handling code here:
        this.cambio(new ListarCPUUI(this.LosCpu, this.LasMarcas));
    }//GEN-LAST:event_JMI_ListarCPUActionPerformed

    private void JMI_BuscarCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BuscarCPUActionPerformed
        // TODO add your handling code here:
        this.cambio(new BuscarCPUUI(this.LosCpu, this.LasMarcas));
    }//GEN-LAST:event_JMI_BuscarCPUActionPerformed

    private void JMI_GuardarCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GuardarCPUActionPerformed
        // TODO add your handling code here:
        if(this.LosCpu.Guardar()){
            this.TE.Msn("El archivo se Guardo");
        }else{
            this.TE.Msn("No tiene Permisos");
        }
    }//GEN-LAST:event_JMI_GuardarCPUActionPerformed

    private void JMI_AgregarImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AgregarImprActionPerformed
        // TODO add your handling code here:
        this.cambio(new AgregarImpresoraUI(this.LasImpresoras, this.LasMarcas));
    }//GEN-LAST:event_JMI_AgregarImprActionPerformed

    private void JMI_ListarImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ListarImprActionPerformed
        // TODO add your handling code here:
        this.cambio(new ListarImpresoraUI(this.LasImpresoras, this.LasMarcas));
    }//GEN-LAST:event_JMI_ListarImprActionPerformed

    private void JMI_BuscarImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BuscarImprActionPerformed
        // TODO add your handling code here:
        this.cambio(new BuscarImpresoraUI(this.LasImpresoras, this.LasMarcas));
    }//GEN-LAST:event_JMI_BuscarImprActionPerformed

    private void JMI_GuardarImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GuardarImprActionPerformed
        // TODO add your handling code here:
        if(this.LasImpresoras.Guardar()){
            this.TE.Msn("El archivo se Guardo");
        }else{
            this.TE.Msn("No tiene Permisos");
        }
    }//GEN-LAST:event_JMI_GuardarImprActionPerformed

    private void JMI_AgregarPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AgregarPersActionPerformed
        // TODO add your handling code here:
        this.cambio(new AgregarPersonasUI(LasPersonas));
    }//GEN-LAST:event_JMI_AgregarPersActionPerformed

    private void JMI_ListarPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ListarPersActionPerformed
        // TODO add your handling code here:
        this.cambio(new ListarPersonasUI(LasPersonas));
    }//GEN-LAST:event_JMI_ListarPersActionPerformed

    private void JMI_BuscarPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BuscarPersActionPerformed
        // TODO add your handling code here:
        this.cambio(new BuscarPersonasUI(LasPersonas));
    }//GEN-LAST:event_JMI_BuscarPersActionPerformed

    private void JMI_GuardarPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GuardarPersActionPerformed
        // TODO add your handling code here:
        if(this.LasPersonas.Guardar()){
            this.TE.Msn("El archivo se Guardo");
        }else{
            this.TE.Msn("No tiene Permisos");
        }
    }//GEN-LAST:event_JMI_GuardarPersActionPerformed

    private void JMI_GestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_GestionActionPerformed

    private void JMI_GuardarPers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_GuardarPers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_GuardarPers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_Acercade;
    private javax.swing.JMenuItem JMI_AgregarCPU;
    private javax.swing.JMenuItem JMI_AgregarImpr;
    private javax.swing.JMenuItem JMI_AgregarMoni;
    private javax.swing.JMenuItem JMI_AgregarPers;
    private javax.swing.JMenuItem JMI_BuscarCPU;
    private javax.swing.JMenuItem JMI_BuscarImpr;
    private javax.swing.JMenuItem JMI_BuscarMoni;
    private javax.swing.JMenuItem JMI_BuscarPers;
    private javax.swing.JMenuItem JMI_Gestion;
    private javax.swing.JMenuItem JMI_GuardarCPU;
    private javax.swing.JMenuItem JMI_GuardarImpr;
    private javax.swing.JMenuItem JMI_GuardarMoni;
    private javax.swing.JMenuItem JMI_GuardarPers;
    private javax.swing.JMenuItem JMI_GuardarPers1;
    private javax.swing.JMenuItem JMI_ListarCPU;
    private javax.swing.JMenuItem JMI_ListarImpr;
    private javax.swing.JMenuItem JMI_ListarMoni;
    private javax.swing.JMenuItem JMI_ListarPers;
    private javax.swing.JMenuItem JMI_Salir;
    private javax.swing.JMenu JM_Archivo;
    private javax.swing.JMenu JM_Ayuda;
    private javax.swing.JMenu JM_CPU;
    private javax.swing.JMenu JM_Gestion;
    private javax.swing.JMenu JM_Impresora;
    private javax.swing.JMenu JM_Monitor;
    private javax.swing.JMenu JM_Persona;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
