/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMonitor;

import DAO.MarcaDAO;
import DAO.MonitorDAO;
import Teclado.Teclado;
import VO.MarcaVO;
import VO.MonitorVO;

/**
 *
 * @author Paula
 */
public class BuscarMoniUI extends javax.swing.JPanel {
private MonitorDAO LosMoni;
private MonitorVO buscado;
private MarcaDAO LasMarcas;
private Teclado TE=new Teclado();
    /**
     * Creates new form BuscarMoniUI
     */
    public BuscarMoniUI(MonitorDAO local, MarcaDAO lasMarcas) {
        this.LosMoni=local;
        this.LasMarcas=lasMarcas;
        initComponents();
        this.JT_ID.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_FormBusq = new javax.swing.JLabel();
        JL_ID = new javax.swing.JLabel();
        JT_ID = new javax.swing.JTextField();
        JL_MARCA = new javax.swing.JLabel();
        JL_SERIE = new javax.swing.JLabel();
        JL_TIPO = new javax.swing.JLabel();
        JL_PULGADA = new javax.swing.JLabel();
        JB_ACTIVAR = new javax.swing.JButton();
        JB_CANCELAR = new javax.swing.JButton();
        JT_PULGADA = new javax.swing.JTextField();
        JT_TIPO = new javax.swing.JTextField();
        JT_SERIE = new javax.swing.JTextField();
        JCB_MARCA = new javax.swing.JComboBox();
        JL_BuscarID = new javax.swing.JLabel();
        JT_BuscarID = new javax.swing.JTextField();
        JB_REGISTRARCAMBIOS = new javax.swing.JButton();
        JB_BUSCAR = new javax.swing.JButton();
        JL_RESOLUCION = new javax.swing.JLabel();
        JT_RESOLUCION = new javax.swing.JTextField();

        JL_FormBusq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_FormBusq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_FormBusq.setText("FORMULARIO BUSQUEDA DE MONITOR");

        JL_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_ID.setText("ID");

        JL_MARCA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_MARCA.setText("MARCA");

        JL_SERIE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_SERIE.setText("SERIE");

        JL_TIPO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_TIPO.setText("TIPO");

        JL_PULGADA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_PULGADA.setText("PULGADA");

        JB_ACTIVAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_ACTIVAR.setText("ACTIVAR");
        JB_ACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ACTIVARActionPerformed(evt);
            }
        });

        JB_CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_CANCELAR.setText("CANCELAR");

        JL_BuscarID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_BuscarID.setText("BUSCAR ID");

        JB_REGISTRARCAMBIOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_REGISTRARCAMBIOS.setText("REGISTRAR CAMBIOS");
        JB_REGISTRARCAMBIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGISTRARCAMBIOSActionPerformed(evt);
            }
        });

        JB_BUSCAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_BUSCAR.setText("BUSCAR");
        JB_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BUSCARActionPerformed(evt);
            }
        });

        JL_RESOLUCION.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_RESOLUCION.setText("RESOLUCION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_FormBusq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_PULGADA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_PULGADA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_RESOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_RESOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JL_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JT_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JB_BUSCAR))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JB_ACTIVAR)
                        .addGap(18, 18, 18)
                        .addComponent(JB_REGISTRARCAMBIOS)
                        .addGap(18, 18, 18)
                        .addComponent(JB_CANCELAR)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JL_FormBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_PULGADA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_PULGADA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_RESOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_RESOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_ACTIVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_REGISTRARCAMBIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_ACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ACTIVARActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JB_ACTIVARActionPerformed

    private void JB_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BUSCARActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(this.JT_BuscarID.getText());
        buscado=this.LosMoni.buscarXID(ID);
        if(buscado !=null){
            this.JT_ID.setText(""+buscado.getCodigo());
            this.JT_ID.setEditable(false);
            this.JT_ID.setVisible(true);
            this.JT_SERIE.setText(buscado.getSerie());
            this.JT_TIPO.setText(buscado.getTipo());
            this.JT_PULGADA.setText(""+buscado.getPulgada());
            this.JT_RESOLUCION.setText(buscado.getResolucion());
            Object marcas[]=this.LasMarcas.getBDMarca();
            this.JCB_MARCA.removeAllItems();
            for(int i=0;i<this.LasMarcas.getSize();i++){
                MarcaVO tmoMarca =(MarcaVO)marcas[i];
                this.JCB_MARCA.addItem(tmoMarca);
                if(tmoMarca.getID()==Integer.parseInt(buscado.getMarca())){
                    this.JCB_MARCA.setSelectedIndex(i);
                }
            }
            System.out.println("el monitor es el "+buscado.getSerie());
        }else{
            System.out.println("El monitor no esta");
        }
    }//GEN-LAST:event_JB_BUSCARActionPerformed

    private void JB_REGISTRARCAMBIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGISTRARCAMBIOSActionPerformed
        // TODO add your handling code here:
        if(TE.confirmar("Esta seguro de realizar \nlos cambios")==0){
            String serie=this.JT_SERIE.getText();
            String tipo=this.JT_TIPO.getText();
            String pulgada=this.JT_PULGADA.getText();
            String resolucion=this.JT_RESOLUCION.getText();
            MarcaVO tmpMar=(MarcaVO) this.JCB_MARCA.getSelectedItem();
            int marca=tmpMar.getID();
            buscado.setSerie(serie);
            buscado.setTipo(tipo);
            buscado.setPulgada(Double.parseDouble(pulgada));
            buscado.setMarca(""+marca);
            buscado.setResolucion(resolucion);
            /*
            this.JT_SERIE.setVisible(false);
            this.JT_ID.setVisible(false);
            this.JT_PULGADA.setVisible(false);
            this.JT_TIPO.setVisible(false);
            this.JCB_MARCA.setVisible(false);
            this.JB_ACTIVAR.setVisible(false);
            this.JB_REGISTRARCAMBIOS.setVisible(false);
            this.JB_CANCELAR.setVisible(false);
            */
            this.JL_ID.setVisible(true);
            this.JL_MARCA.setVisible(true);
            this.JL_PULGADA.setVisible(true);
            this.JL_SERIE.setVisible(true);
            this.JL_TIPO.setVisible(true);
        }
    }//GEN-LAST:event_JB_REGISTRARCAMBIOSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ACTIVAR;
    private javax.swing.JButton JB_BUSCAR;
    private javax.swing.JButton JB_CANCELAR;
    private javax.swing.JButton JB_REGISTRARCAMBIOS;
    private javax.swing.JComboBox JCB_MARCA;
    private javax.swing.JLabel JL_BuscarID;
    private javax.swing.JLabel JL_FormBusq;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_MARCA;
    private javax.swing.JLabel JL_PULGADA;
    private javax.swing.JLabel JL_RESOLUCION;
    private javax.swing.JLabel JL_SERIE;
    private javax.swing.JLabel JL_TIPO;
    private javax.swing.JTextField JT_BuscarID;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_PULGADA;
    private javax.swing.JTextField JT_RESOLUCION;
    private javax.swing.JTextField JT_SERIE;
    private javax.swing.JTextField JT_TIPO;
    // End of variables declaration//GEN-END:variables
}
