/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMonitor;

import DAO.MarcaDAO;
import DAO.MonitorDAO;
import VO.MarcaVO;

/**
 *
 * @author Paula
 */
public class ListarMonitorUI extends javax.swing.JPanel {

    private MonitorDAO LosMoni;
    private MarcaDAO LasMarcas;

    /**
     * Creates new form ListarMonitorU
     */
    public ListarMonitorUI(MonitorDAO local, MarcaDAO lasMarcas) {
        this.LosMoni = local;
        this.LasMarcas= lasMarcas;
        initComponents();
        this.JCB_Marcas.removeAllItems();
        Object CanasMarcas[]=LasMarcas.getBDMarca();
        for(int i=0;i<this.LasMarcas.getSize();i++){
            MarcaVO tmpLocal =(MarcaVO)CanasMarcas[i];
            JCB_Marcas.addItem(tmpLocal);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_ListMoni = new javax.swing.JLabel();
        JB_Listar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JT_Moni = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JCB_Marcas = new javax.swing.JComboBox<MarcaVO>();

        setPreferredSize(new java.awt.Dimension(400, 300));

        JL_ListMoni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_ListMoni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_ListMoni.setText("MONITORES ALMACENADOS");

        JB_Listar.setText("LISTAR");
        JB_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListarActionPerformed(evt);
            }
        });

        JT_Moni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JT_Moni);

        jLabel1.setText("Filtro por Marcas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_ListMoni, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JL_ListMoni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListarActionPerformed
        // TODO add your handling code here:
        MarcaVO tmp=(MarcaVO) this.JCB_Marcas.getSelectedItem();
        this.JT_Moni.setModel(this.LosMoni.crearTabla(LasMarcas, tmp));
    }//GEN-LAST:event_JB_ListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Listar;
    private javax.swing.JComboBox<MarcaVO> JCB_Marcas;
    private javax.swing.JLabel JL_ListMoni;
    private javax.swing.JTable JT_Moni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
