/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCPU;

import DAO.CPUDAO;
import DAO.MarcaDAO;
import Teclado.Teclado;
import VO.CPUVO;
import VO.MarcaVO;

/**
 *
 * @author Paula
 */
public class BuscarCPUUI extends javax.swing.JPanel {
private CPUDAO LosCPU;
private CPUVO buscado;
private MarcaDAO LasMarcas;
private Teclado TE=new Teclado();
    /**
     * Creates new form BuscarCPUUI
     */
    public BuscarCPUUI(CPUDAO local, MarcaDAO lasMarcas) {
        this.LosCPU=local;
        this.LasMarcas=lasMarcas;
        initComponents();
        this.JT_ID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_FormBusq = new javax.swing.JLabel();
        JL_BuscarID = new javax.swing.JLabel();
        JT_BuscarID = new javax.swing.JTextField();
        JB_BUSCAR = new javax.swing.JButton();
        JT_ID = new javax.swing.JTextField();
        JCB_MARCA = new javax.swing.JComboBox();
        JT_SERIE = new javax.swing.JTextField();
        JT_DISCO = new javax.swing.JTextField();
        JT_MEMORIA = new javax.swing.JTextField();
        JL_MEMORIA = new javax.swing.JLabel();
        JL_DISCO = new javax.swing.JLabel();
        JL_SERIE = new javax.swing.JLabel();
        JL_MARCA = new javax.swing.JLabel();
        JL_ID = new javax.swing.JLabel();
        JB_ACTIVAR = new javax.swing.JButton();
        JB_REGISTRARCAMBIOS = new javax.swing.JButton();
        JB_CANCELAR = new javax.swing.JButton();

        JL_FormBusq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_FormBusq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_FormBusq.setText("FORMULARIO BUSQUEDA DE MONITOR");

        JL_BuscarID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_BuscarID.setText("BUSCAR ID");

        JB_BUSCAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_BUSCAR.setText("BUSCAR");
        JB_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BUSCARActionPerformed(evt);
            }
        });

        JL_MEMORIA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_MEMORIA.setText("MEMORIA");

        JL_DISCO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_DISCO.setText("DISCO");

        JL_SERIE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_SERIE.setText("SERIE");

        JL_MARCA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_MARCA.setText("MARCA");

        JL_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_ID.setText("ID");

        JB_ACTIVAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_ACTIVAR.setText("ACTIVAR");
        JB_ACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ACTIVARActionPerformed(evt);
            }
        });

        JB_REGISTRARCAMBIOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_REGISTRARCAMBIOS.setText("REGISTRAR CAMBIOS");
        JB_REGISTRARCAMBIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGISTRARCAMBIOSActionPerformed(evt);
            }
        });

        JB_CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_CANCELAR.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_FormBusq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_DISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_DISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_MEMORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_MEMORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JL_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_BUSCAR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JB_ACTIVAR)
                        .addGap(18, 18, 18)
                        .addComponent(JB_REGISTRARCAMBIOS)
                        .addGap(18, 18, 18)
                        .addComponent(JB_CANCELAR)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JL_FormBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_DISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_DISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_MEMORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_MEMORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_ACTIVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_REGISTRARCAMBIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BUSCARActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(this.JT_BuscarID.getText());
        buscado=this.LosCPU.buscarXID(ID);
        if(buscado !=null){
            this.JT_ID.setText(""+buscado.getCodigo());
            this.JT_ID.setEditable(false);
            this.JT_ID.setVisible(true);
            this.JT_SERIE.setText(buscado.getSerie());
            this.JT_DISCO.setText(buscado.getDisco());
            this.JT_MEMORIA.setText(""+buscado.getMemoria());
            Object marcas[]=this.LasMarcas.getBDMarca();
            this.JCB_MARCA.removeAllItems();
            for(int i=0;i<this.LasMarcas.getSize();i++){
                MarcaVO tmoMarca =(MarcaVO)marcas[i];
                this.JCB_MARCA.addItem(tmoMarca);
                if(tmoMarca.getID()==Integer.parseInt(buscado.getMarca())){
                    this.JCB_MARCA.setSelectedIndex(i);
                }
            }
            System.out.println("el CPU es el "+buscado.getSerie());
        }else{
            System.out.println("El CPU no esta");
        }
    }//GEN-LAST:event_JB_BUSCARActionPerformed

    private void JB_ACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ACTIVARActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JB_ACTIVARActionPerformed

    private void JB_REGISTRARCAMBIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGISTRARCAMBIOSActionPerformed
        // TODO add your handling code here:
        if(TE.confirmar("Esta seguro de realizar \nlos cambios")==0){
            String serie=this.JT_SERIE.getText();
            String Disco=this.JT_DISCO.getText();
            String Memoria=this.JT_MEMORIA.getText();
            MarcaVO tmpMar=(MarcaVO) this.JCB_MARCA.getSelectedItem();
            int marca=tmpMar.getID();
            buscado.setSerie(serie);
            buscado.setDisco(Disco);
            buscado.setMemoria(Memoria);
            buscado.setMarca(""+marca);
            this.JT_SERIE.setVisible(false);
            this.JT_ID.setVisible(false);
            this.JT_MEMORIA.setVisible(false);
            this.JT_DISCO.setVisible(false);
            this.JCB_MARCA.setVisible(false);
            this.JB_ACTIVAR.setVisible(false);
            this.JB_REGISTRARCAMBIOS.setVisible(false);
            this.JB_CANCELAR.setVisible(false);

            this.JL_ID.setVisible(true);
            this.JL_MARCA.setVisible(true);
            this.JL_MEMORIA.setVisible(true);
            this.JL_SERIE.setVisible(true);
            this.JL_DISCO.setVisible(true);
        }
    }//GEN-LAST:event_JB_REGISTRARCAMBIOSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ACTIVAR;
    private javax.swing.JButton JB_BUSCAR;
    private javax.swing.JButton JB_CANCELAR;
    private javax.swing.JButton JB_REGISTRARCAMBIOS;
    private javax.swing.JComboBox JCB_MARCA;
    private javax.swing.JLabel JL_BuscarID;
    private javax.swing.JLabel JL_DISCO;
    private javax.swing.JLabel JL_FormBusq;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_MARCA;
    private javax.swing.JLabel JL_MEMORIA;
    private javax.swing.JLabel JL_SERIE;
    private javax.swing.JTextField JT_BuscarID;
    private javax.swing.JTextField JT_DISCO;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_MEMORIA;
    private javax.swing.JTextField JT_SERIE;
    // End of variables declaration//GEN-END:variables
}
