/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaImpresoras;

import DAO.ImpresoraDAO;
import DAO.MarcaDAO;
import Teclado.Teclado;
import VO.ImpresoraVO;
import VO.MarcaVO;
import VistaCPU.*;

/**
 *
 * @author Paula
 */
public class AgregarImpresoraUI extends javax.swing.JPanel {
private ImpresoraDAO LasImpre;
    private MarcaDAO LasMarcas;
    private Teclado TE=new Teclado();
    /**
     * Creates new form AgregarCPUUI
     */
    public AgregarImpresoraUI(ImpresoraDAO local, MarcaDAO lasMarcas) {
        this.LasImpre = local;
        this.LasMarcas = lasMarcas;
        initComponents();
             Object Marca[] = this.LasMarcas.getBDMarca();
        
        for (int i=0;i<this.LasMarcas.getSize();i++){
            MarcaVO tmp = (MarcaVO) Marca[i];
            this.JCB_MARCA.addItem(tmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JL_ID = new javax.swing.JLabel();
        JL_MARCA = new javax.swing.JLabel();
        JL_SERIE = new javax.swing.JLabel();
        JL_TIPO = new javax.swing.JLabel();
        JB_REGISTRAR = new javax.swing.JButton();
        JB_CANCELAR = new javax.swing.JButton();
        JT_TIPO = new javax.swing.JTextField();
        JT_SERIE = new javax.swing.JTextField();
        JCB_MARCA = new javax.swing.JComboBox<MarcaVO>();
        JT_ID = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO PARA AGREGAR MONITORES");

        JL_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_ID.setText("ID");

        JL_MARCA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_MARCA.setText("MARCA");

        JL_SERIE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_SERIE.setText("SERIE");

        JL_TIPO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JL_TIPO.setText("TIPO");

        JB_REGISTRAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_REGISTRAR.setText("REGISTRAR");
        JB_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGISTRARActionPerformed(evt);
            }
        });

        JB_CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JB_CANCELAR.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(JB_REGISTRAR)
                                    .addGap(44, 44, 44)
                                    .addComponent(JB_CANCELAR))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JL_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(JT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JCB_MARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT_SERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(68, 68, 68)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JB_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGISTRARActionPerformed
        // TODO add your handling code here:
        try {
            String Tipo = this.JT_TIPO.getText();
            String Serie = this.JT_SERIE.getText();
            MarcaVO tmp = (MarcaVO) this.JCB_MARCA.getSelectedItem();
            String Marca = ""+tmp.getID();
            int ID = Integer.parseInt(this.JT_ID.getText());
            ImpresoraVO tmpImpr = this.LasImpre.buscarXID(ID);
        if (tmpImpr != null){//control por si agregan una Impresora con un id que ya está registrado
                 TE.Msn("Ya hay una Impresora con el ID: " + ID + ", registrada. \n Por favor, ingrese una impresora con otro ID");
        }else{
            if (LasImpre.almacenar(Tipo, ID, Serie, Marca)){
                TE.Msn("Impresora Registrada");
                this.JT_TIPO.setText("");
                this.JT_SERIE.setText("");
                 this.JCB_MARCA.setSelectedIndex(0);
                this.JT_ID.setText("");

            }else{
                TE.Msn("No hay cupo");
            }
        }
        }catch (Exception e){
            TE.Msn("Datos Érroneos");
        }
    }//GEN-LAST:event_JB_REGISTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CANCELAR;
    private javax.swing.JButton JB_REGISTRAR;
    private javax.swing.JComboBox<MarcaVO> JCB_MARCA;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_MARCA;
    private javax.swing.JLabel JL_SERIE;
    private javax.swing.JLabel JL_TIPO;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_SERIE;
    private javax.swing.JTextField JT_TIPO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
