/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPersonas;

import DAO.PersonasDAO;
import Teclado.Teclado;
import VO.PersonasVO;
import VistaCPU.*;

/**
 *
 * @author Paula
 */
public class AgregarPersonasUI extends javax.swing.JPanel {

    private PersonasDAO LasPersonas;
    private Teclado TE = new Teclado();

    /**
     * Creates new form AgregarCPUUI
     */
    public AgregarPersonasUI(PersonasDAO local) {
        this.LasPersonas = local;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_FormAgrePerson = new javax.swing.JLabel();
        JL_CEDULA = new javax.swing.JLabel();
        JL_NOMBRE = new javax.swing.JLabel();
        JL_APELLIDO = new javax.swing.JLabel();
        JB_REGISTRAR = new javax.swing.JButton();
        JB_CANCELAR = new javax.swing.JButton();
        JT_APELLIDO = new javax.swing.JTextField();
        JT_CEDULA = new javax.swing.JTextField();
        JT_NOMBRE = new javax.swing.JTextField();

        JL_FormAgrePerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_FormAgrePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_FormAgrePerson.setText("FORMULARIO PARA AGREGAR PERSONAS");

        JL_CEDULA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_CEDULA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_CEDULA.setText("CEDULA");

        JL_NOMBRE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_NOMBRE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_NOMBRE.setText("NOMBRES");

        JL_APELLIDO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_APELLIDO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_APELLIDO.setText("APELLIDOS");

        JB_REGISTRAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_REGISTRAR.setText("REGISTRAR");
        JB_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGISTRARActionPerformed(evt);
            }
        });

        JB_CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_CANCELAR.setText("CANCELAR");

        JT_APELLIDO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JT_CEDULA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JT_NOMBRE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_FormAgrePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(JB_REGISTRAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_CANCELAR)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_CEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_CEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JL_FormAgrePerson)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_CEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_CEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGISTRARActionPerformed
        // TODO add your handling code here:
        try {
             int Cedula = Integer.parseInt(this.JT_CEDULA.getText());
            String Nombre = this.JT_NOMBRE.getText();
            String Apellido = this.JT_APELLIDO.getText();
            PersonasVO tmpPerso = this.LasPersonas.buscarXCedula(Cedula);
            if (tmpPerso != null){//control por si agregan una Persona con una Cédula que ya está registrada
                 TE.Msn("Ya Existe una persona con esa cédula registrada. \n Por favor, ingrese un usuario con una cédula diferente");
        }else{
             if (LasPersonas.almacenar(Cedula, Nombre, Apellido)){
                TE.Msn("Persona Registrada");
                this.JT_CEDULA.setText("");
                this.JT_NOMBRE.setText("");
                this.JT_APELLIDO.setText("");
                
            }else{
                TE.Msn("No hay cupo");
            }
        }
        }catch (Exception e){
            TE.Msn("Datos Érroneos");
       }

    }//GEN-LAST:event_JB_REGISTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CANCELAR;
    private javax.swing.JButton JB_REGISTRAR;
    private javax.swing.JLabel JL_APELLIDO;
    private javax.swing.JLabel JL_CEDULA;
    private javax.swing.JLabel JL_FormAgrePerson;
    private javax.swing.JLabel JL_NOMBRE;
    private javax.swing.JTextField JT_APELLIDO;
    private javax.swing.JTextField JT_CEDULA;
    private javax.swing.JTextField JT_NOMBRE;
    // End of variables declaration//GEN-END:variables
}
