/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPersonas;

import DAO.PersonasDAO;
import VO.PersonasVO;
import VistaCPU.*;

/**
 *
 * @author Paula
 */
public class BuscarPersonasUI extends javax.swing.JPanel {

    private PersonasDAO LasPerso;

    /**
     * Creates new form BuscarCPUUI
     */
    public BuscarPersonasUI(PersonasDAO local) {
        this.LasPerso = local;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_CedulaBuscar = new javax.swing.JLabel();
        JL_Cedula = new javax.swing.JLabel();
        JL_Nombre = new javax.swing.JLabel();
        JL_Apellido = new javax.swing.JLabel();
        JT_Apellido = new javax.swing.JTextField();
        JT_Nombre = new javax.swing.JTextField();
        JT_Cedula = new javax.swing.JTextField();
        JT_CedulaBuscar = new javax.swing.JTextField();
        JB_Buscar = new javax.swing.JButton();
        JL_TituForBusPerso = new javax.swing.JLabel();
        JB_Activar = new javax.swing.JButton();
        JB_RegisCambios = new javax.swing.JButton();
        JB_Cancelar = new javax.swing.JButton();

        JL_CedulaBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_CedulaBuscar.setText("Buscar por Cedula");

        JL_Cedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Cedula.setText("Cedula");

        JL_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Nombre.setText("Nombre");

        JL_Apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Apellido.setText("Apellido");

        JT_Apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JT_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JT_Cedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JT_CedulaBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JB_Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_Buscar.setText("Buscar");
        JB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BuscarActionPerformed(evt);
            }
        });

        JL_TituForBusPerso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_TituForBusPerso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_TituForBusPerso.setText("Formulario para Buscar Personas");

        JB_Activar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_Activar.setText("ACTIVAR");

        JB_RegisCambios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_RegisCambios.setText("REGISTRAR CAMBIOS");

        JB_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_Cancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_TituForBusPerso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JL_CedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JT_CedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(JB_Buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JB_Activar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JT_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JB_RegisCambios)
                                        .addGap(29, 29, 29)
                                        .addComponent(JB_Cancelar)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_TituForBusPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_CedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_CedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Activar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_RegisCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BuscarActionPerformed
        // TODO add your handling code here:
        int Cedula = Integer.parseInt(this.JT_CedulaBuscar.getText());
        PersonasVO tmpPerso = this.LasPerso.buscarXCedula(Cedula);
        if (tmpPerso != null) {
            this.JT_Cedula.setText("" + tmpPerso.getCedula());
            this.JT_Cedula.setVisible(true);
            this.JT_Cedula.setEditable(false);

            this.JT_Nombre.setText(tmpPerso.getNombre());
            this.JT_Nombre.setVisible(true);
            this.JT_Apellido.setText(tmpPerso.getApellido());
            this.JT_Apellido.setVisible(true);
        } else {
            System.err.println("La Persona no está");
        }
    }//GEN-LAST:event_JB_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Activar;
    private javax.swing.JButton JB_Buscar;
    private javax.swing.JButton JB_Cancelar;
    private javax.swing.JButton JB_RegisCambios;
    private javax.swing.JLabel JL_Apellido;
    private javax.swing.JLabel JL_Cedula;
    private javax.swing.JLabel JL_CedulaBuscar;
    private javax.swing.JLabel JL_Nombre;
    private javax.swing.JLabel JL_TituForBusPerso;
    private javax.swing.JTextField JT_Apellido;
    private javax.swing.JTextField JT_Cedula;
    private javax.swing.JTextField JT_CedulaBuscar;
    private javax.swing.JTextField JT_Nombre;
    // End of variables declaration//GEN-END:variables
}
