/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPersonas;

import DAO.PersonasDAO;
import VistaCPU.*;

/**
 *
 * @author Paula
 */
public class ListarPersonasUI extends javax.swing.JPanel {

    private PersonasDAO LasPersonas;

    /**
     * Creates new form ListarCPUUI
     */
    public ListarPersonasUI(PersonasDAO local) {
        this.LasPersonas = local;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_TituForLisPerso = new javax.swing.JLabel();
        JB_CargarList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_ListaPerso = new javax.swing.JTextArea();

        JL_TituForLisPerso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JL_TituForLisPerso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_TituForLisPerso.setText("Formulario para Listar Personas");

        JB_CargarList.setText("Cargar Lista");
        JB_CargarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CargarListActionPerformed(evt);
            }
        });

        JTA_ListaPerso.setEditable(false);
        JTA_ListaPerso.setColumns(20);
        JTA_ListaPerso.setRows(5);
        jScrollPane1.setViewportView(JTA_ListaPerso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_TituForLisPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JB_CargarList)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JL_TituForLisPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_CargarList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CargarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CargarListActionPerformed
        // TODO add your handling code here:
        this.JTA_ListaPerso.setText(this.LasPersonas.ListaPersonas());
    }//GEN-LAST:event_JB_CargarListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CargarList;
    private javax.swing.JLabel JL_TituForLisPerso;
    private javax.swing.JTextArea JTA_ListaPerso;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
